---
- name: Install MariaDB server package
  yum:
    name: '{{db_package}}'
    state: present
- name: Start MariaDB Service
  service:
     name: '{{db_service}}'
     state: started
     enabled: true
