---
- hosts: all
  handlers:
  - name: start-apache
    service:
      name: httpd
      state: started
  tasks:
  - name: install apache
    yum:
     name: httpd
     state: present
    notify: start-apache

  - name: create user
    user:
      name: test101
      state: present

