---
- hosts: all
  gather_facts: no
  serial: 
   - 1
   - 4
   - 2
  become: yes
  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: present

  - name: install apache
    yum:
      name: httpd
      state: present

