---
- hosts: all
  tasks:
  - name: Task1
    command: /bin/sleep 5
    when: inventory_hostname == 'server1'

  - name: Task2
    command: /bin/sleep 5
    when: inventory_hostname == 'server2'

  - name: Task3
    command: /bin/sleep 5
    when: inventory_hostname == 'server3'

  - name: Task4
    command: /bin/sleep 5
    when: inventory_hostname == 'server4'

  - name: Task5
    command: /bin/sleep 5
    when: inventory_hostname == 'server1'

  - name: Task6
    command: /bin/sleep 5
    when: inventory_hostname == 'server2'
