---
- hosts: all
  vars_files:
    - vars.yaml
  tasks: 
  - name: install package using variables
    yum:
      name: '{{ pkg }}'
      state: present

  - name: Display variables
    debug:
      msg: 'package {{ pkg }} installed '

  - name: Create a user named {{username}}
    user:
     name: '{{username}}'


   
