---
- hosts: all
  become: yes
  vars:
    packages:
    - nginx
    - git
    - httpd
    - tree
    - wget
  tasks:
    - name: removing packages
      yum: 
        name: '{{ item }}'
        state : absent
      with_items: '{{packages}}'

    - name: Installing packages
      yum: 
        name: '{{ item }}'
        state : present
      with_items: '{{packages}}'
