---
- hosts: localhost
  become: yes
  name: create a testgrp group and create multiple users (testuser01 to testuser09) using with_sequence
  tasks:
  - group:
      name: testgrp
      state: present
  - user:
      name: "{{ item }}"
      state: present
      groups: "testgrp"
    with_sequence: start=1 end=9 format=testuser%03x
