---
- hosts: all
  become: yes
  gather_facts: yes 
  tasks:
  - name: display variable  
    debug:
      msg: 'os distribution is {{ansible_os_family}}'
 
  - name: display variable  
    debug:
      msg: 'os distribution is {{ansible_virtualization_type}}'
 
  - name: install git
    yum:
     name: git
     state: present
    when: ansible_os_family == 'RedHat'
   
  - name: install git
    apt:
     name: git
     state: present
    when: ansible_os_family == 'Debian'
   
